defaults:
  - data: convnext
  - model: convnext
  - optimizer: adamw
  - trainer: trainer
  - loss: focalloss
  - scheduler: cosineAnnealing_lr
  - callback: early_stopping

experiment_name: experiment_0