defaults:
  - data: efficientnet
  - model: efficientnet
  - optimizer: adamw
  - trainer: trainer
  - loss: focalloss
  - scheduler: cosineAnnealing_lr
  - callback: early_stopping

experiment_name: experiment_0